validation: sovereign
version: 1
chain_id: "horse-1"
accounts:
- name: smoothiepool
  coins:
  - 400000000000horse
- name: faucet
  coins:
  - 100000000horse
faucet:
  name: faucet
  coins:
  - 100000horse
client:
  source_url: "https://github.com/uwu-shepards/horse"
  typescript:
    path: ts-client
  openapi:
    path: docs/static/openapi.yml
validators:
- name: smoothiepool
  bonded: 200000000000horse
